version: '3.8'

services:
  triagem-medica:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: triagem-medica-iot
    ports:
      - "8501:8501"
    volumes:
      # Mapear diretórios de dados para persistência
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - triagem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  triagem-network:
    driver: bridge

volumes:
  triagem-data:
    driver: local
  triagem-logs:
    driver: local 